django_gentoostats/apps/stats/urls.py
# from tastypie.api import Api

# from django.conf.urls import include
from django.conf.urls import patterns, url

# from .api import *

# api = Api(api_name='')
# api.register(HostResource())
# api.register(SubmissionResource())

urlpatterns = patterns('apps.stats.views',
    url( r'^$'
       , 'index'
       , name='index_url'
    ),

    url( r'^faq/$'
       , 'faq'
       , name='faq_url'
    ),

    url( r'^about/$'
       , 'about'
       , name='about_url'
    ),

    url( r'^stats/$'
       , 'stats'
       , name='stats_url'
    ),

    url( r'^stats/overall/$'
       , 'overall_stats'
       , name='overall_stats_url'
    ),

    # Host(s): #{{{
    url( r'^stats/host/$'
       , 'host_search'
       , name='host_search_url'
    ),

    url( r'^stats/(?:host/)(?P<host_id>[\da-fA-F]{8}-?[\da-fA-F]{4}-?[\da-fA-F]{4}-?[\da-fA-F]{4}-?[\da-fA-F]{12})/$'
       , 'host_details'
       , name='host_details_url'
    ),
    #}}}

    # ARCH(es): #{{{
    url( r'^stats/arch/(?P<arch>\S+)/$'
       , 'arch_details'
       , name='arch_details_url'
    ),
    #}}}

    # FEATURE(s): #{{{
    url( r'^stats/feature/(?P<feature>\S+)/$'
       , 'feature_details'
       , name='feature_details_url'
    ),
    #}}}

    # Keyword(s): #{{{
    url( r'^stats/keyword/(?P<keyword>\w+)/$'
       , 'keyword_details'
       , name='keyword_details_url'
    ),
    #}}}

    # Repository(ies): #{{{
    url( r'^stats/repository/$'
       , 'repository_stats'
       , name='repository_stats_url'
    ),

    url( r'^stats/repository/(?P<name>\S+)/$'
       , 'repository_details'
       , name='repository_details_url'
    ),
    #}}}

    # Servers: #{{{
    url( r'^stats/servers/$'
       , 'server_stats'
       , name='server_stats_url'
    ),

    url( r'^stats/servers/mirror/(?P<server_id>\S+)/$'
       , 'mirror_details'
       , name='mirror_details_url'
    ),

    url( r'^stats/servers/sync/(?P<server_id>\S+)/$'
       , 'sync_details'
       , name='sync_details_url'
    ),
    #}}}

    # Profile(s): #{{{
    url( r'^stats/profile/(?P<profile>\S+)/$'
       , 'profile_details'
       , name='profile_details_url'
    ),
    #}}}

    # LANG(s): #{{{
    url( r'^stats/lang/(?P<lang>\S+)/$'
       , 'lang_details'
       , name='lang_details_url'
    ),
    #}}}

    # Submission(s): #{{{
    url( r'^stats/submission/(?P<host_id>[\da-fA-F]{8}-?[\da-fA-F]{4}-?[\da-fA-F]{4}-?[\da-fA-F]{4}-?[\da-fA-F]{12})/(?P<relative_id>\d+)/$'
       , 'submission_details'
       , name='submission_details_url'
    ),
    #}}}

    # USE flag(s): #{{{
    url( r'^stats/use/$'
       , 'use_stats'
       , name='use_stats_url'
    ),

    url( r'^stats/use/(?P<useflag>\S+)/$'
       , 'use_details'
       , name='use_details_url'
    ),
    #}}}

    # Apps: #{{{
    url( r'^stats/apps/$'
       , 'app_stats'
       , name='app_stats_url'
    ),
    #}}}

    # Packages: #{{{
    url( r'^stats/package/$'
       , 'package_search'
       , name='package_search_url'
    ),

    url( r'^stats/package/(?P<package>\S+)'
       , 'package_details'
       , name='package_details_url'
    ),
    #}}}

    # API: #{{{
    # url( r'^api', include(api.urls)),
    #}}}
)

django_gentoostats/gentoostats/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url( r'^upload(/|$)'
       , include( 'apps.receiver.urls'
                , namespace = 'receiver'
                , app_name  = 'receiver'
         )
    ),

    url( r''
       , include( 'apps.stats.urls'
                , namespace = 'stats'
                , app_name  = 'stats'
         )
    ),
)

django_gentoostats/apps/stats/forms.py
from django import forms

from .models import Host
from .util import canonicalize_uuid

class HostSearchForm(forms.Form):
    host_id = forms.CharField(label='UUID')

    def clean_host_id(self):
        host_id = canonicalize_uuid(self.cleaned_data['host_id'])

        if not Host.objects.filter(id=host_id).exists():
            raise forms.ValidationError("Invalid/Non-existent UUID.")

        return host_id

django_gentoostats/apps/stats/views.py
from __future__ import division

import json
import operator
import datetime

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page, cache_control
from django.core.exceptions import ObjectDoesNotExist
from django.utils.timezone import utc
from django.views.generic import ListView, DetailView
from django.db.models import Q, Count
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404

from portage.exception import InvalidAtom
from portage.dep import Atom as PortageAtom

from .util import split_list, canonicalize_uuid, percentify
from .forms import HostSearchForm
from .models import Feature, Host, Keyword, Lang, MirrorServer, Package, \
                    Repository, Submission, SyncServer, UseFlag

FRESH_SUBMISSION_MAX_AGE = 30 # in days

@cache_control(public=True)
@cache_page(1 * 60)
def index(request):
    """
    Index page of Gentoostats.
    """

    return render(request, 'stats/index.html')

@cache_control(public=True)
@cache_page(24 * 60 * 60)
def faq(request):
    """
    Frequently Asked Questions page.
    """

    return render(request, 'stats/not_implemented.html')

@cache_control(public=True)
@cache_page(24 * 60 * 60)
def about(request):
    """
    Project about page.
    """

    return render(request, 'stats/about.html')

@cache_control(public=True)
@cache_page(24 * 60 * 60)
def stats(request):
    """
    Stats index page.
    """

    return render(request, 'stats/stats_index.html')

@cache_control(public=True)
@cache_page(1 * 60)
def overall_stats(request):
    """
    Show overall stats for the website.
    """

    latest_submission_q = Q(submissions__in=Submission.objects.latest_submission_ids)

    features = Feature.objects.filter(latest_submission_q).annotate(num_hosts_fast=Count('submissions')).order_by('name')
    langs    = Lang.objects.filter(latest_submission_q).annotate(num_hosts_fast=Count('submissions')).order_by('name')
    keywords = Keyword.objects.filter(latest_submission_q).annotate(num_hosts_fast=Count('submissions')).order_by('name')

    context = dict(
        hosts         = Host.objects.all(),
        submissions   = Submission.objects.all(),
        country_stats = Submission.objects.latest_submissions_unique.filter(country__isnull=False).values_list('country').annotate(num_hosts=Count('country')).order_by('country'),
        arch_stats    = Submission.objects.latest_submissions_unique.values_list('arch').annotate(num_hosts=Count('arch')).order_by('arch'),
        profile_stats = Submission.objects.latest_submissions_unique.values_list('profile').annotate(num_hosts=Count('profile')).order_by('profile'),
        useflags      = UseFlag.objects.all(),
        packages      = Package.objects.all(),
        features      = features,
        langs         = langs,
        keywords      = keywords,
        latest_public_submissions_all = Submission.objects.latest_public_submissions_all,
    )

    return render(request, 'stats/overall_stats.html', context)

# Hosts: #{{{
@cache_control(public=True)
@cache_page(24 * 60 * 60)
def host_search(request):
    """
    Search for a host by its full UUID.
    """

    if request.method == 'POST':
        form = HostSearchForm(request.POST)
        if form.is_valid():
            return redirect( 'stats:host_details_url'
                           , host_id   = form.cleaned_data['host_id']
                           , permanent = False
            )
    else:
        form = HostSearchForm(
            # initial = dict(host_id='Enter UUID'),
        )

    context = dict(
        form=form,
    )

    return render(request, 'stats/host_search.html', context)

@cache_control(private=True)
@cache_page(1 * 60)
def host_details(request, host_id):
    """
    Show statistics about a certain host.
    """

    # Accept UUIDs regardless of hyphenation or case sensitivity, but still
    # redirect the user to their canonical URL:
    host_id_canonical = canonicalize_uuid(host_id)

    if host_id != host_id_canonical:
        return redirect( 'stats:host_details_url'
                       , host_id   = host_id_canonical
                       , permanent = True
        )

    context = dict(
        host = get_object_or_404( Host.objects.select_related('submissions')
                                , id = host_id
        ),
    )

    return render(request, 'stats/host_details.html', context)
#}}}

@cache_control(public=True)
@cache_page(1 * 60)
def arch_details(request, arch):
    """
    Show more detailed statistics about a specific arch.
    """

    try:
        context = dict(
            stats_type      = "Arch",
            value           = arch,
            num_submissions = Submission.objects.filter(arch=arch).count(),
            num_all_hosts   = Submission.objects.filter(arch=arch).order_by().aggregate(Count('host', distinct=True)).values()[0],
            num_hosts       = Submission.objects.latest_submissions_unique.filter(arch=arch).count(),
            added_on        = Submission.objects.filter(arch=arch).values('added_on').order_by('added_on')[:1].get().added_on,
        )
    except ObjectDoesNotExist:
        raise Http404

    return render(request, 'stats/generic_details.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def keyword_details(request, keyword):
    """
    Show statistics about a particular keyword (e.g. amd64).
    """

    context = dict(
        keyword = get_object_or_404(Keyword, name=keyword),
    )

    return render(request, 'stats/keyword_details.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def feature_details(request, feature):
    """
    Show statistics about a particular FEATURE.
    """

    context = dict(
        feature = get_object_or_404(Feature, name=feature),
    )

    return render(request, 'stats/feature_details.html', context)

# Servers: #{{{
@cache_control(public=True)
@cache_page(1 * 60)
def server_stats(request):
    """
    Show statistics about the known sync and mirror servers.
    """

    context = dict(
        mirror_servers = MirrorServer.objects.all(),
        sync_servers   = SyncServer.objects.all(),
    )

    return render(request, 'stats/server_stats.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def mirror_details(request, server_id):
    """
    Show more detailed statistics about a specific mirror server.
    """

    context = dict(
        server = get_object_or_404(MirrorServer, id=server_id)
    )

    return render(request, 'stats/server_details.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def sync_details(request, server_id):
    """
    Show more detailed statistics about a specific SYNC server.
    """

    context = dict(
        server = get_object_or_404(MirrorServer, id=server_id),
    )

    return render(request, 'stats/server_details.html', context)
#}}}

# Repositories: #{{{
@cache_control(public=True)
@cache_page(1 * 60)
def repository_stats(request):
    """
    TODO: add a description.
    """

    context = dict(
        repositories = Repository.objects.all(),
    )

    return render(request, 'stats/repository_stats.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def repository_details(request, name):
    """
    TODO: add a description.
    """

    repo = get_object_or_404(Repository, name=name)

    context = dict(
        stats_type      = "Repository",
        value           = repo,
        num_submissions = repo.num_submissions,
        num_all_hosts   = repo.num_all_hosts,
        num_hosts       = repo.num_hosts,
        added_on        = repo.added_on,
    )

    return render(request, 'stats/generic_details.html', context)
#}}}

@cache_control(public=True)
@cache_page(1 * 60)
def package_search(request):
    """
    TODO: Use a real form here.
    """

    return render(request, 'stats/package_search.html')

@cache_control(public=True)
@cache_page(1 * 60)
def package_details(request, package):
    """
    TODO: add a description.
    """

    context = dict(
        query = package,
    )

    try:
        patom = PortageAtom( package
                           , allow_wildcard = False # at least for now
                           , allow_repo     = True
        )
    except InvalidAtom:
        return render( request
                     , 'stats/package_details.html' # reuse the same template
                     , dict(context, invalid=True)  # set context['invalid']
                     , status=400                   # "Bad Request"
        )

    # Find all Package objects that satisfy the PortageAtom by using Q objects:
    q_list = [Q(cp=patom.cp)]

    if patom.repo:
        q_list.append(Q(repository__name=patom.repo))

    if patom.version:
        q_list.append(Q(version=patom.version))

    if patom.slot:
        q_list.append(Q(slot=patom.slot))

    q_final = reduce(operator.and_, q_list)
    matching_packages = Package.objects.filter(q_final).distinct()

    context['packages'] = matching_packages
    return render(request, 'stats/package_details.html', context)

@cache_control(public=True)
@cache_page(1 * 60)
def lang_details(request, lang):
    """
    TODO: add a description.
    """

    return render(request, 'stats/not_implemented.html')

# Submissions: #{{{
# TODO: @login_required(login_url='/login')
@cache_control(private=True)
@cache_page(24 * 60 * 60)
def submission_details(request, host_id, relative_id):
    """relative_id is the submission number (starting from 1) relative to the
    host"""
    relative_id = int(relative_id)
    if relative_id < 0:
        raise Http404

    submission_id = Submission.objects\
            .filter(host=host_id)\
            .values_list('id', flat=True)\
            .order_by('id')[relative_id-1:relative_id]\
            .get()

    # Prefetch everything required so that the template doesn't have to hit the
    # database. The resulting SQL isn't very pretty, but it works.

django_gentoostats/apps/stats/templates/stats/arch_stats.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}ARCH Statistics | Gentoostats {% endblock title %}

{% block content %}
    <h1>TODO</h1>
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/base.html
{% load package_helpers %}
{% load general %}
{% load nav %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% block head %}
            <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />
            <title>{% block title %}Gentoostats{% endblock %}</title>
        {% endblock head %}
    </head>

    <body>
        {% block body %}
            <div id="header">
                {% block header %}
                    <a id="logo" href="{% url 'stats:index_url' %}" title="Home"></a>
                    <ul id="nav">
                        <li>{% nav_link 'stats:index_url' 'Home' %}<span class="sep">|</span></li>
                        <li>{% nav_link 'stats:stats_url' 'Stats' %}<span class="sep">|</span></li>
                        {#<li>{% nav_link 'stats:faq_url' 'FAQ' %}<span class="sep">|</span></li>#}
                        <li>{% nav_link 'stats:about_url' 'About' %}</li>
                    </ul>
                    <a href="https://github.com/gg7/gentoostats_server"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" alt="Fork me on GitHub"></a>
                {% endblock header %}
            </div>

            <div id="content">
                {% block content %}
                {% endblock content %}
            </div>

            <div id="footer">
                {% block footer %}
                    <p>Gentoostats is an official Gentoo project. "Gentoo" and the "g" logo are trademarks of Gentoo Foundation, Inc.</p>
                {% endblock footer %}
            </div>
        {% endblock body %}
    </body>
</html>

django_gentoostats/apps/stats/templates/stats/feature_details.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Detailed FEATURE Statistics | Gentoostats {% endblock title %}

{% block content %}
    {% with this_sucks="Detailed FEATURE Statistics for '"|append:feature|append:"'" %}
        {% h1 this_sucks %}
    {% endwith %}

    <ul>
        <li>Present in {{ feature.num_submissions|default_if_none:"?" }} submission{{ feature.num_submissions|default_if_none:2|pluralize }}.</li>
        <li>Currently used by {{ feature.num_hosts|default_if_none:"?" }} host{{ feature.num_hosts|default_if_none:2|pluralize }}.</li>
        <li>Has been used by {{ feature.num_all_hosts|default_if_none:"?" }} host{{ feature.num_all_hosts|default_if_none:2|pluralize }}.</li>
        <li>Added on {{ feature.added_on|default_if_none:"?" }}.</li>
    </ul>
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/generic_details.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Detailed {{ stats_type }} Statistics | Gentoostats {% endblock title %}

{% block content %}
    {% with this_sucks="Detailed "|append:stats_type|append:" Statistics for '"|append:value|append:"'" %}
        {% h1 this_sucks %}
    {% endwith %}

    <ul>
        <li>Present in {{ num_submissions|default_if_none:"?" }} submission{{ num_submissions|default_if_none:2|pluralize }}.</li>
        <li>Currently used by {{ num_hosts|default_if_none:"?" }} host{{ num_hosts|default_if_none:2|pluralize }}.</li>
        <li>Has been used by {{ num_all_hosts|default_if_none:"?" }} host{{ num_all_hosts|default_if_none:2|pluralize }}.</li>
        <li>Added on {{ added_on|default_if_none:"?" }}.</li>
    </ul>
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/host_details.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Detailed Host Statistics | Gentoostats {% endblock title %}

{% block content %}
    {% with this_sucks="Detailed Host Statistics for '"|append:host.id|append:"'" %}
        {% h1 this_sucks %}
    {% endwith %}

    {% with latest_submission=host.latest_submission %}
        {% if latest_submission %}
            <h2>Submissions:</h2>
            <ul>
            {% for id, added_on, protocol in host.submission_history %}
                <li><a href="{% url 'stats:submission_details_url' host_id=host.id relative_id=forloop.counter %}">{{ added_on }} (protocol: {{ protocol }})</a></li>
            {% endfor %}
            </ul>

            <h2>Latest submission</h2>
            {% include 'stats/submission_simple.html' with submission=latest_submission %}
        {% else %}
            <h2>No existing submissions.</h2>
        {% endif %}
    {% endwith %}
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/host_search.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Host Search | Gentoostats {% endblock title %}

{% block content %}
    {% h1 "Host Search" %}

    {% if form.errors %}
        <p class='error'>Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/index.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Home | Gentoostats{% endblock title %}

{% block content %}
    {% h1 "About Gentoostats" %}
    <p>The Gentoostats project aims to gather statistics about the installed
    packages on Gentoo systems in order to provide useful information to both
    users and developers.</p>
    {% h2 "Why contribute?" %}
    <ul>
    <li>Help developers see which packages and overlays are important</li>
    <li>Help developers choose when to stabilise a package</li>
    <li>Create a snapshot of your system (your world file + package USE flags)</li>
    <li>Help us settle down <a href="/stats/apps/#editors-ides">some serious issues</a></li>
    </ul>
    {% h2 "How to contribute?" %}
    <p>Contribution is easy -- just download the client, configure it, and
    submit your stats.</p>
    {% h2 "Installation" %}
    <p>The following dependencies are required:</p>
    <ul>
        <li>Python 2.7+, including Python 3+ (emerge -av '>=dev-lang/python-2.7')</li>
        <li>Portage (emerge -av 'sys-apps/portage')</li>
        <li>Gentoolkit (emerge -av 'app-portage/gentoolkit')</li>
    </ul>
    <p>Make sure that you have the above dependencies installad. Then clone the
    client repository:</p>
    <p class="code">git clone https://github.com/gg7/gentoostats.git</p>
    <p>Place the directory wherever you want, but remember to add the 'pym'
    subdirectory directory to your $PYTHONPATH. For example,</p>
    <p class="code">export PYTHONPATH="~/gentoostats/pym"</p>
    <p class="code">export PATH="~/gentoostats/bin:$PATH"</p>
    <p>Now, onto configuration:</p>
    <p class="code">gentoostats configure</p>
    <p>You will be asked a couple of questions and the following two files will
    be generated:</p>
    <ul>
        <li>/etc/gentoostats/auth.cfg</li>
        <li>/etc/gentoostats/payload.cfg</li>
    </ul>
    <p>Finally, run</p>
    <p class="code">gentoostats submit</p>
    {% h2 "What will be reported?" %}
    <p>You will be asked exactly what to report when you configure Gentoostats.
    Here's what <i>can</i> be reported:</p>
    <ul>
    <li>Make.conf variables:</li>
        <ul>
        <li>ACCEPT_KEYWORDS</li>
        <li>ACCEPT_LICENSE</li>
        <li>ARCH</li>
        <li>CFLAGS</li>
        <li>CHOST</li>
        <li>CTARGET</li>
        <li>CXXFLAGS</li>
        <li>EMERGE_DEFAULT_OPTS</li>
        <li>FEATURES</li>
        <li>FFLAGS</li>
        <li>GENTOO_MIRRORS</li>
        <li>LDFLAGS</li>
        <li>MAKEOPTS</li>
        <li>PORTAGE_RSYNC_EXTRA_OPTS</li>
        <li>SYNC (rsync server)</li>
        </ul>
    <li>System USE flags (USE)</li>
    <li>Installed Packages</li>
        <ul>
        <li>Package build time</li>
        <li>Package keyword</li>
        <li>Package repository (e.g. "gentoo")</li>
        <li>Package size</li>
        <li>Package USE flags (USE, IUSE, PKGUSE)</li>
        </ul>
    <li>Selected Packages (your @world set, plus all selected sets)</li>
    <li>Time of last Portage tree synchronisation (LASTSYNC)</li>
    <li>LANG</li>
    <li>PLATFORM (e.g. 'Linux-3.2.1-gentoo-r2-x86_64-Intel-R-_Core-TM-_i3_CPU_M_330_@_2.13GHz-with-gentoo-2.0.3')</li>
    <li>PROFILE (e.g. 'default/linux/amd64/10.0/desktop')</li>
    </ul>
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/not_implemented.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Not Implemented | Gentoostats{% endblock title %}

{% block content %}
    {% h1 "Sorry, this page is yet to be implemented" %}
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/overall_stats.html
{% extends "stats/base.html" %}

{% load general %}
{# {% load prettytimes_tags %} #}
{% load humanize %}

{% block title %}Overall Statistics | Gentoostats {% endblock title %}

{% block content %}
    {% h1 "Overall statistics" %}

    {% if hosts.count %}
        <h2>{{ submissions.count }} Submissions from {{ hosts.count }} hosts</h2>
        <p>Latest public submissions:</p>
        <ul>
            {% for submission in latest_public_submissions_all|slice:"10" %}
                <li><a href={{ submission.get_absolute_url }}>{{ submission.arch_classified }} | {{ submission.installations.count }} packages | {{ submission.added_on|naturaltime }}</a></li>
            {% endfor %}
        </ul>

        <h2>{{ packages.count }} Packages with {{ useflags.count }} USE flags</h2>
        <p>Todo</p>

        {% if country_stats %}
            <h2>Countries</h2>
            <table border="1">
                <th>Country</th>
                <th>Hosts</th>
                {% for country, num_hosts in country_stats %}
                    <tr>
                        <td>{{ country|default_if_none:"unknown" }}</td>
                        <td>{{ num_hosts }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}

        <h2>Architectures</h2>
        <table border="1">
            <th>Arch</th>
            <th>Hosts</th>
            {% for arch, num_hosts in arch_stats %}
                <tr>
                    <td><a href="{% url 'stats:arch_details_url' arch=arch %}">{{ arch }}</a></td>
                    <td>{{ num_hosts }}</td>
                </tr>
            {% endfor %}
        </table>

        <h2>Keywords</h2>
        <table border="1">
            <th>Keyword</th>
            <th>Hosts</th>
            {% for keyword in keywords %}
                <tr>
                    <td><a href="{{ keyword.get_absolute_url }}">{{ keyword }}</a></td>
                    <td>{{ keyword.num_hosts_fast|default_if_none:keyword.num_hosts|default_if_none:"?" }}</td>
                </tr>
            {% endfor %}
        </table>

        <h2>Profiles</h2>
        <table border="1">
            <th>Profile</th>
            <th>Hosts</th>
            {% for profile, num_hosts in profile_stats %}
                <tr>
                    <td><a href="{% url 'stats:profile_details_url' profile=profile %}">{{ profile }}</a></td>
                    <td>{{ num_hosts }}</td>
                </tr>
            {% endfor %}
        </table>

        <h2>FEATUREs</h2>
        <table border="1">
            <th>FEATURE</th>
            <th>Hosts</th>
            {% for feature in features %}
                <tr>
                    <td><a href="{{ feature.get_absolute_url }}">{{ feature }}</a></td>
                    <td>{{ feature.num_hosts_fast|default_if_none:feature.num_hosts|default_if_none:"?" }}</td>
                </tr>
            {% endfor %}
        </table>

        <h2>$LANG</h2>
        <table border="1">
            <th>$LANG</th>
            <th>Hosts</th>
            {% for lang in langs %}
                <tr>
                    <td>{{ lang }}</td>
                    <td>{{ lang.num_hosts_fast|default_if_none:lang.num_hosts|default_if_none:"?" }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>No submissions/hosts are present yet.</h2>
    {% endif %}
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/package_details.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Detailed Package Statistics | Gentoostats {% endblock title %}

{% block content %}
    {% if invalid %}
        <h1 class="error">Error: Invalid atom: '{{ query }}'"</h1>
    {% else %}
        {% with this_sucks="Packages Matching '"|append:query|append:"'" %}
            {% h1 this_sucks %}
        {% endwith %}

        {% if not packages %}
            <h2>No results, sorry.</h2>
        {% else %}
            <ul>
            {% for package in packages %}
                <li>{{ package }} (used by {{ package.num_hosts|default_if_none:"?" }} host{{ package.num_hosts|default_if_none:2|pluralize }})</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
{% endblock content %}

django_gentoostats/apps/stats/templates/stats/stats_index.html
{% extends "stats/base.html" %}
{% load general %}

{% block title %}Home | Gentoostats{% endblock title %}

{% block content %}
    {% h1 "Available Statistics" %}

    <ul>
        <li><a href="{% url 'stats:overall_stats_url' %}">Overall stats</a></li>
        <li><a href="{% url 'stats:app_stats_url' %}">App stats</a></li>
        <li><a href="{% url 'stats:host_search_url' %}">Host search</a></li>
        <li><a href="{% url 'stats:use_stats_url' %}">USE stats</a></li>
        <li><a href="{% url 'stats:repository_stats_url' %}">Repository stats</a></li>
        <li><a href="{% url 'stats:package_search_url' %}">Package stats</a></li>
        <li><a href="{% url 'stats:server_stats_url' %}">Server stats</a></li>
    </ul>
{% endblock content %}